Truncate menu items
europeana/portal.js pull request #1018
Opened 2021-03-11 11:56 UTC by alansutherland

2021-03-11 14:29 UTC, LeoniePeters requested changes

2021-03-11 14:29 UTC, LeoniePeters commented on components/PageNavigation.vue
> +      margin-bottom: 0;
I don't see why this is needed.
If it is, in that case you could just set margin: 0 and remove margin-right and margin-bottom.

2021-03-11 14:29 UTC, LeoniePeters commented on components/PageNavigation.vue
> +          display: block;
Remove this display: block. It overwrites the above (line 222) set display: flex which keeps the icon and text properly aligned and the element height correct.

2021-03-11 14:29 UTC, LeoniePeters commented on components/PageNavigation.vue
> +          height: 1.5rem;
Remove this height as it's unnecessary when display is set to flex as mentioned above.

2021-03-11 14:29 UTC, LeoniePeters commented on components/PageNavigation.vue
> +            margin-right: 0.5rem;
Is this needed?

2021-03-15 08:47 UTC, mirjamverloop approved these changes

2021-03-15 08:50 UTC, merged