Accept/reject a recommended item for a gallery
europeana/portal.js pull request #1073
Opened 2021-05-07 10:06 UTC by spyrosbek

2021-05-14 10:21 UTC, annachristaki commented on src/pages/set/_.vue
> +          this.$store.dispatch('set/fetchActiveRecommendations', `/${this.$route.params.pathMatch}`);
Make sure this is called on page reload

2021-05-14 10:23 UTC, annachristaki commented on src/store/set.js
> +          recList.splice(index, 1, response.items[0]);
Check that response contains items before getting first one

2021-05-14 10:23 UTC, annachristaki commented on src/store/set.js
> +          recList.splice(index, 1, response.items[0]);
Check that response contains items

2021-05-14 10:28 UTC, annachristaki commented on src/store/set.js
> +          }).indexOf(params.itemIds[0]);
Maybe better to use findIndex

2021-05-14 10:30 UTC, annachristaki requested changes
Needs a few changes to work without errors

2021-06-02 12:37 UTC, rwd requested changes

2021-06-02 12:37 UTC, rwd commented on src/components/account/UserButtons.vue
> +      <template
Let's move the recommendation buttons and accompanying logic out into a new component, `src/components/recommendation/RecommendationButtons.vue`

Then, in ItemPreviewCard.vue:
```html
    <template v-slot:buttons>
      <RecommendationButtons
        v-if="recommendedItem"
        v-model="identifier"
      />
      <UserButtons
        v-else
        v-model="identifier"
      />
    </template>
```

2021-06-23 11:54 UTC, annachristaki approved these changes

2021-07-05 09:39 UTC, lbiedinger approved these changes

2021-07-07 10:25 UTC, rwd approved these changes

2021-07-07 15:04 UTC, lbiedinger approved these changes

2021-07-08 06:40 UTC, lbiedinger approved these changes

2021-07-08 06:47 UTC, merged