multilingual item page with default from api
europeana/portal.js pull request #1182
Opened 2021-08-06 13:36 UTC by lbiedinger

2021-08-11 15:03 UTC, lbiedinger commented on src/components/item/ItemLanguageSelector.vue
> +               -->
indentation

2021-08-16 13:02 UTC, LeoniePeters requested changes

2021-08-16 16:46 UTC, LeoniePeters approved these changes

2021-08-18 11:33 UTC, rwd approved these changes

2021-08-18 11:33 UTC, merged