WIP: ab testing + matomo
europeana/portal.js pull request #1194
Opened 2021-08-24 14:43 UTC by mirjamverloop

2021-09-07 08:28 UTC, LeoniePeters requested changes

2021-09-07 08:28 UTC, LeoniePeters commented on src/plugins/ab-testing.js
> +  if (!consentCookie?.matomo) {
The matomo AB testing cookie might/should be separate from the matomo analytics cookie. So this check should change once we do the set up with the plugin

2021-09-07 08:28 UTC, LeoniePeters commented on src/plugins/ab-testing.js
> +    } else { // else, not in cookie
Define `variant` and then just check if undefined (i.e. no cookie yet)
```
let variant = ctx.$cookies.get(`eu-ab-${experiment.name}`);
if (!variant) {
```

2021-09-07 08:28 UTC, LeoniePeters commented on src/plugins/ab-testing.js
> +  }
Why inject useless functions? 
```
  if (experiments.length === 0 || !ctx.$cookies.get('klaro')?.matomo) {
    return;
  }
```
In layout/default.vue we can then use `this.$experiments?.()` to first check if the function exists (is injected) and then call it.

2021-09-17 07:53 UTC, lbiedinger approved these changes

2021-09-17 07:56 UTC, merged