Search contexts, with removal badges for entities and queries
europeana/portal.js pull request #1460
Opened 2022-03-09 14:34 UTC by lbiedinger

2022-03-16 10:20 UTC, LeoniePeters requested changes

2022-03-16 10:20 UTC, LeoniePeters commented on src/components/search/ContextLabel.vue
> +  }
Remove these styles as they are unused.

2022-03-16 16:20 UTC, lbiedinger commented on src/components/search/RemovalChip.vue
> +</style>
I've left the clear-indicator styling as is with a TODO as that new class isn't available yet until that other PR is merged.

2022-03-23 08:31 UTC, rwd approved these changes

2022-03-23 11:25 UTC, mirjamverloop approved these changes

2022-03-23 11:26 UTC, merged