refactor: store page metadata
europeana/portal.js pull request #1759
Opened 2022-11-11 11:42 UTC by rwd

2022-11-11 14:00 UTC, rwd commented
Re EC-6031

2022-11-16 09:15 UTC, LeoniePeters requested changes

2022-11-16 12:03 UTC, rwd commented on packages/portal/src/pages/collections/_type/_.vue
> +      },
Nothing; removed.

2022-11-16 13:20 UTC, LeoniePeters requested changes

2022-11-16 13:20 UTC, LeoniePeters commented on packages/portal/tests/unit/components/generic/ErrorMessage.spec.js
> +    $store: {
Clean up the `$store` mock together with `sinon` and `shallowMountNuxt`

2022-11-16 13:20 UTC, LeoniePeters commented on packages/portal/tests/unit/layouts/default.spec.js
> +        },
Revert

2022-11-16 13:20 UTC, LeoniePeters commented on packages/portal/tests/unit/layouts/error.spec.js
> +        wrapper.vm.$store.state.pageMeta.data = pageMeta;
Remove this line

2022-11-17 08:29 UTC, LeoniePeters approved these changes

2022-11-17 10:58 UTC, merged