feat: detect and solve (if possible) IIIF issues
europeana/portal.js pull request #1978
Opened 2023-06-07 16:15 UTC by LeoniePeters

2023-07-25 10:31 UTC, rwd requested changes

2023-07-26 10:44 UTC, LeoniePeters commented on packages/portal/src/components/iiif/IIIFViewer.vue
> +      window.onunhandledrejection = (event) => {
Done.

2023-07-26 10:44 UTC, LeoniePeters commented on packages/portal/src/components/iiif/IIIFViewer.vue
> +          this.handleManifestError('No canvases');
Done.

2023-07-26 10:45 UTC, LeoniePeters commented on packages/portal/src/components/iiif/IIIFErrorMessage.vue
> +      <i18n
Well spotted. I've made the translation string so that the 'or' is conditionally there, only when there is a link.

2023-08-09 08:36 UTC, merged