feat: item media annotation search
europeana/portal.js pull request #2456
Opened 2024-10-17 08:32 UTC by rwd

2024-10-24 08:46 UTC, lbiedinger requested changes

2024-10-25 07:30 UTC, rwd commented on packages/portal/src/components/item/ItemMediaPresentation.vue
> +        pageForAnnotationTarget,
Indeed, and gone.

2024-10-25 07:30 UTC, rwd commented on packages/portal/src/components/item/ItemMediaPresentation.vue
> +        selectAnnotation,
Indeed, and gone.

2024-10-28 10:24 UTC, lbiedinger approved these changes

2024-10-28 10:30 UTC, merged