EC-4663 Similar Items/Explore more items
europeana/portal.js pull request #788
Opened 2020-08-25 09:44 UTC by lbiedinger

2020-08-25 09:45 UTC, lbiedinger commented on components/item/ItemPreviewCard.vue
> +        if (this.variant === 'similar' || this.variant === 'explore') return [];
I'd use a check to see if the variant is in an array, but similar will be removed after the new page becomes the default.

2020-08-25 12:35 UTC, alansutherland requested changes
The h2 title should have margin-bottom 0.5rem according to the design

Below the cards there’s a 112px gap before the footer on the design, currently it looks around 40px. Perhaps add this as padding-bottom to .container wrapping the title, metadata and cards? that way the gap will also be on pages without similar items.

2020-08-25 12:35 UTC, alansutherland commented on assets/scss/cards.scss
> +        margin-right: 8px;
switch to 0.5rem

2020-08-25 12:35 UTC, alansutherland commented on assets/scss/cards.scss
> +        margin-left: 8px;
switch to 0.5rem

2020-08-25 12:35 UTC, alansutherland commented on assets/scss/cards.scss
> +        margin-right: 4px;
switch to 0.25rem

2020-08-25 12:35 UTC, alansutherland commented on assets/scss/cards.scss
> +        margin-left: 4px;
switch to 0.25rem for this and the two lines below

2020-08-25 12:35 UTC, alansutherland commented on assets/scss/variables.scss
> +$grid-gutter-narrow: 4px;
switch to 0.25rem

2020-08-26 13:07 UTC, alansutherland approved these changes

2020-08-27 08:10 UTC, mirjamverloop approved these changes

2020-08-27 08:36 UTC, mirjamverloop approved these changes

2020-08-27 09:16 UTC, merged