display api errors on set page
europeana/portal.js pull request #790
Opened 2020-08-25 13:42 UTC by annachristaki

2020-08-27 09:24 UTC, rwd requested changes

2020-08-27 09:24 UTC, rwd commented on pages/set/_.vue
> +          v-if="$fetchState.pending"
This condition is redundant if the container has the same.

2020-08-27 09:24 UTC, rwd commented on pages/set/_.vue
> +      const set = await fetch(apiUrl, { headers })
Why is all of this here, duplicating the functionality from the set plugin?

If it's just to get the status code, then apiError includes that as a property named `statusCode`, so just catch the error.

2020-08-28 07:54 UTC, rwd approved these changes

2020-08-28 10:22 UTC, lbiedinger approved these changes

2020-08-28 10:23 UTC, merged