Update the collection modal's behavior
europeana/portal.js pull request #804
Opened 2020-09-02 14:10 UTC by spyrosbek

2020-09-02 18:27 UTC, lbiedinger approved these changes

2020-09-02 19:22 UTC, lbiedinger requested changes
Actually this doesn't add the item to a newly created set.

2020-09-02 19:24 UTC, lbiedinger commented on components/account/UserButtons.vue
> +          @cancel="setCreatedOrUpdated"
When is this needed?

2020-09-03 13:00 UTC, lbiedinger approved these changes

2020-09-03 14:44 UTC, mirjamverloop approved these changes

2020-09-03 14:50 UTC, merged