API URLs from custom HTTP header
europeana/portal.js pull request #837
Opened 2020-09-18 13:25 UTC by rwd

2020-09-28 12:33 UTC, lbiedinger requested changes

2020-09-28 13:10 UTC, rwd commented on store/search.js
> +        commit('set', [property, rootGetters[`collections/${collection}/${property}`](this.$apis.config)]);
Indeed. Fixed in 2d90beb.

2020-09-28 13:30 UTC, lbiedinger approved these changes

2020-10-06 14:44 UTC, lbiedinger commented on plugins/axiosLogger.js
> +    const url = `${config.baseURL}${uri}`;
this is showing up as 'undefined' on any contentful requests.

2020-10-20 11:55 UTC, lbiedinger approved these changes

2020-10-20 12:50 UTC, merged