View public set test
europeana/portal.js pull request #900
Opened 2020-11-09 11:15 UTC by alansutherland

2020-11-09 11:41 UTC, alansutherland commented
The test is failing as it seems there's an issue with viewing public sets on the test portal which isn't happening on local or prod [this set](https://portaljs-test.eanadev.org/en/set/66 ) shows me a blank version of the user likes page 
<img width="686" alt="Screenshot 2020-11-09 at 20 41 01" src="https://user-images.githubusercontent.com/4670058/98536968-f049b580-22cb-11eb-95e7-3977e2d90514.png">

2020-11-10 15:19 UTC, rwd requested changes

2020-11-10 15:19 UTC, rwd commented on nuxt.config.js
> +        origin: process.env.OAUTH_ORIGIN || 'https://auth.europeana.eu',
This does not appear to be used anywhere. If not, remove it.

2020-11-10 15:19 UTC, rwd commented on tests/features/pages/set-page.feature
> +    When I open an `user gallery page`
"a" not "an"

2020-11-10 15:19 UTC, rwd commented on tests/features/pages/set-page.feature
> +    And I see a `item count`
"an" not "a"

2020-11-10 15:19 UTC, rwd commented on tests/features/pages/set-page.feature
> +    And I see a `item previews grid`
"an" not "a"

2020-11-10 15:19 UTC, rwd commented on tests/features/pages/set-page.feature
> +    And I see a `item preview`
"an" not "a"

2020-11-11 15:31 UTC, lbiedinger commented on .github/workflows/support/ci/.env
>  EUROPEANA_SET_API_KEY=${EUROPEANA_SET_API_KEY}
we could also probably get rid of these.

2020-11-11 15:46 UTC, lbiedinger approved these changes

2020-11-12 11:38 UTC, rwd approved these changes

2020-11-12 11:43 UTC, merged