Authentication tests
europeana/portal.js pull request #911
Opened 2020-11-17 17:09 UTC by lbiedinger

2020-11-18 12:05 UTC, lbiedinger commented on tests/features/user/authentication.feature
> +# the tests relying on these are commented out. Fake credentials are currently in /
"in docker/stack/docker-compose.yml."

2020-11-18 13:07 UTC, alansutherland requested changes

2020-11-18 13:07 UTC, alansutherland commented on components/PageNavigation.vue
> -        v-else-if="enableLoginLink"
Removing this conditional has caused a regression. When I log in the log in button remains in the desktop navigation and both log in and log out are shown in the mobile navigation

<img width="1294" alt="Screenshot 2020-11-18 at 21 32 47" src="https://user-images.githubusercontent.com/4670058/99533982-0d783580-29ea-11eb-8ca8-9f20021949bf.png">

<img width="1294" alt="Screenshot 2020-11-18 at 21 34 26" src="https://user-images.githubusercontent.com/4670058/99533973-094c1800-29ea-11eb-8aba-2192d97b5d68.png">

2020-11-19 08:41 UTC, alansutherland approved these changes

2020-11-23 09:57 UTC, merged