Show map
europeana/portal.js pull request #917
Opened 2020-11-23 11:24 UTC by rwd

2020-11-24 15:21 UTC, LeoniePeters requested changes

2020-11-25 12:09 UTC, rwd commented on components/item/MetadataBox.vue
> +      MapEmbed: () => import('../geo/MapEmbed')
This style of import is used elsewhere, and it results in lazy loading of code-split components where they are only used conditionally, preventing their inclusion in pages or parent components where not used.

2020-11-25 12:23 UTC, rwd commented on components/geo/MapEmbed.vue
> +        showLocationMap: false
Indeed, it's not. Removed.

2020-11-25 12:23 UTC, rwd commented on components/geo/MapEmbed.vue
> +    }
Thank you, and done!

2020-11-26 08:23 UTC, LeoniePeters approved these changes

2020-11-26 10:41 UTC, merged