Redirect to previous page after login
europeana/portal.js pull request #933
Opened 2020-12-07 16:19 UTC by rwd

2021-01-12 14:53 UTC, LeoniePeters approved these changes

2021-01-14 10:31 UTC, alansutherland approved these changes

2021-01-14 10:33 UTC, alansutherland requested changes
one test is failing 

```
Scenario: Unselecting facets # search/faceting.feature:92
   ✔ Before # config/cucumber.conf.js:49
   ✔ Given I am on `/en/search?page=1&reusability=open&qf=TYPE%3A%22IMAGE%22&qf=COUNTRY%3A%22Belgium%22` # support/step-definitions.js:23
   ✖ When I click the `COUNTRY dropdown button` # support/step-definitions.js:79
       Timed out while waiting for element <[data-qa="COUNTRY dropdown button"]> to be present for 5000 milliseconds. - expected "visible" but got: "not found" 
```

2021-01-14 16:20 UTC, rwd commented
@alansutherland test failures were unrelated, rerunning the job got them to pass.

2021-01-14 16:20 UTC, merged