Century pages WIP
europeana/portal.js pull request #939
Opened 2020-12-11 08:53 UTC by alansutherland

2020-12-11 09:00 UTC, lbiedinger commented on middleware/legacy/rules/explore.js
> +  const pattern = /^\/portal(\/[a-z]{2})?\/explore\/(newcontent|colours|sources|topics|times|people|periods)(\.html)?$/;
this won't be needed as there were never 'times' pages on the classic portal

2020-12-16 14:12 UTC, rwd requested changes

2020-12-16 14:12 UTC, rwd commented on middleware/legacy/rules/entity.js
> +  const pattern = /^\/portal(\/[a-z]{2})?(\/explore\/(people|topics|times))(\/[0-9]+)/;
This should not add "times" but "periods" which is what the classic portal used.

2020-12-16 14:12 UTC, rwd commented on middleware/legacy/rules/entity.js
> +      match[2].replace('/explore', '/collections').replace('/people', '/person').replace('/topics', '/topic').replace('/times', '/timespan'),
This should replace "periods" with "time" (not "times" with "timespan")

2020-12-16 14:12 UTC, rwd commented on plugins/europeana/record.js
> +      const times = (edm.timespans || []).map(reduceEntity).map(Object.freeze);
Revert this change, as here we use agents and concepts (as opposed to people and topics) so should also use timespans.

2020-12-16 14:12 UTC, rwd commented on plugins/europeana/record.js
> +      const entities = [].concat(concepts, places, agents, times)
Revert this change, as here we use agents and concepts (as opposed to people and topics) so should also use timespans.

2020-12-16 14:12 UTC, rwd commented on plugins/europeana/record.js
> +        times,
Here we return agents and concepts (as opposed to people and topics) so should also return timespans (as opposed to times).

2020-12-21 11:12 UTC, rwd approved these changes

2020-12-21 11:21 UTC, merged